version: "3.7"
services:
  
  flask:
    build: 
      context: flask
      # dockerfile: 
    restart: always
    ports:
      - "5000"
    environment:
      - FLASK_APP=app.py
    # command: flask run --host 0.0.0.0

  nginx:
    build: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - "80:80"
      - "7070:7070"
    environment:
      # - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - FLASK_HOST=flask
      - FLASK_PORT=5000      

# docker compose up -d --build --scale flask=3